In [1]:
import numpy as np

# question 4

# matrix
x = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])


# (a) 
inverse = np.linalg.inv(x)
print(f'The inversion of x = {inverse}')
# transpose
transpose=np.transpose(x)
print(f'The transpose of x = {transpose}')
# (b) 
determinant = np.linalg.det(x)
print(f'The determinant of x = {determinant}')
# (c) 
values, vectors = np.linalg.eig(x)
print(f'decomposition values = {values}')
print(f'decomposition = {vectors}')

# (d)
scalar = 4
new_transformation = scalar *x
print(f'Transformation = {new_transformation}')




 

The inversion of x = [[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
The transpose of x = [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
The determinant of x = 0.2299999999999999
decomposition values = [2.04100779 0.82188052 0.13711169]
decomposition = [[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]
Transformation = [[4.  0.8 2. ]
 [0.8 4.  3.2]
 [2.  3.2 4. ]]


In [11]:
# question five

# assume 
# 3x+2y-2z=4
# 2x+3x-3y=5
# x+2y-3z=4

import numpy as np

# coefficients array
A = np.array([[3, 2, -2],[2, 3, -3],[1, 2, -3]])

# Constants 
B = np.array([4, 5, 4])

# Solving the  equations
X = np.linalg.solve(A, B)

# Print the solution
print(f"x,y,z={X} respectively")




x,y,z=[ 0.4  0.6 -0.8] respectively
